version: '3.8'

services:
  syst-pos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Mount volumes for development
    # volumes:
    #   - ./logs:/app/logs

  # Optional: Add a reverse proxy (nginx) for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - syst-pos
  #   restart: unless-stopped

# Optional: Add a database service if needed
# database:
#   image: postgres:15-alpine
#   environment:
#     POSTGRES_DB: syst_pos
#     POSTGRES_USER: syst_user
#     POSTGRES_PASSWORD: syst_password
#   ports:
#     - "5432:5432"
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   restart: unless-stopped

# volumes:
#   postgres_data:
